import React, { useState, useMemo } from 'react';
import {
  XIcon,
  CheckIcon,
  FileCodeIcon,
} from '../shared/Icons';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  skillName: string;
  content: string;
}

type ExportFormat = 'skillmd' | 'mcp' | 'openai' | 'python' | 'typescript';

export default function ExportModal({ isOpen, onClose, skillName, content }: ExportModalProps) {
  const [format, setFormat] = useState<ExportFormat>('mcp');
  const [copied, setCopied] = useState(false);

  // Parse skill fields for export generators
  const parsed = useMemo(() => {
    let name = skillName || 'unnamed-skill';
    let description = 'AI skill specification';
    let trigger = '';
    let tags: string[] = [];
    let model = 'claude-3-5-sonnet-20241022';
    let temperature = 0.7;
    let maxTokens = 2048;
    let body = content;

    const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (fmMatch) {
      body = fmMatch[2];
      const lines = fmMatch[1].split('\n');
      for (const l of lines) {
        const idx = l.indexOf(':');
        if (idx === -1) continue;
        const k = l.slice(0, idx).trim();
        const v = l.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
        if (k === 'name') name = v;
        else if (k === 'description') description = v;
        else if (k === 'trigger') trigger = v;
        else if (k === 'model') model = v;
        else if (k === 'temperature') temperature = parseFloat(v) || 0.7;
        else if (k === 'max_tokens') maxTokens = parseInt(v, 10) || 2048;
        else if (k === 'tags') tags = v.replace(/[\[\]]/g, '').split(',').map(t => t.trim()).filter(Boolean);
      }
    }

    return { name, description, trigger, tags, model, temperature, maxTokens, body };
  }, [skillName, content]);

  const exportCode = useMemo(() => {
    switch (format) {
      case 'skillmd':
        return content;

      case 'mcp':
        return JSON.stringify(
          {
            name: parsed.name,
            description: parsed.description,
            parameters: {
              type: 'object',
              properties: {
                prompt: {
                  type: 'string',
                  description: 'Instruction payload or user request for ' + parsed.name,
                },
              },
              required: ['prompt'],
            },
            metadata: {
              tags: parsed.tags,
              trigger: parsed.trigger,
              default_model: parsed.model,
              temperature: parsed.temperature,
            },
          },
          null,
          2
        );

      case 'openai':
        return JSON.stringify(
          {
            type: 'function',
            function: {
              name: parsed.name.replace(/[^a-zA-Z0-9_]/g, '_'),
              description: parsed.description,
              parameters: {
                type: 'object',
                properties: {
                  instruction: {
                    type: 'string',
                    description: 'Specific input for ' + parsed.name,
                  },
                },
                required: ['instruction'],
              },
            },
          },
          null,
          2
        );

      case 'python':
        return `"""
${parsed.name} — AI Skill Invocation Wrapper
Generated by Delulu AI Skill Studio
"""
import os
import asyncio
from typing import Dict, Any

SKILL_NAME = "${parsed.name}"
MODEL = "${parsed.model}"
TEMPERATURE = ${parsed.temperature}

SYSTEM_PROMPT = \"\"\"${content.replace(/"""/g, '\\"\\"\\"')}\"\"\"

async def execute_skill(user_input: str, api_key: str = None) -> Dict[str, Any]:
    """Invokes the ${parsed.name} agent skill."""
    # Configure your preferred LLM provider client (Anthropic / OpenAI / Ollama)
    print(f"Executing {SKILL_NAME} with model {MODEL}...")
    return {
        "skill": SKILL_NAME,
        "input": user_input,
        "status": "ready"
    }

if __name__ == "__main__":
    asyncio.run(execute_skill("Review TypeScript implementation"))
`;

      case 'typescript':
        return `/**
 * ${parsed.name} — TypeScript Definition
 * Generated by Delulu AI Skill Studio
 */

export interface ${parsed.name.replace(/(?:^|-)(\w)/g, (_, c) => c.toUpperCase())}Skill {
  name: '${parsed.name}';
  description: string;
  model: string;
  temperature: number;
  maxTokens: number;
  tags: string[];
}

export const ${parsed.name.replace(/-(\w)/g, (_, c) => c.toUpperCase())}Config: ${parsed.name.replace(/(?:^|-)(\w)/g, (_, c) => c.toUpperCase())}Skill = {
  name: '${parsed.name}',
  description: '${parsed.description.replace(/'/g, "\\'")}',
  model: '${parsed.model}',
  temperature: ${parsed.temperature},
  maxTokens: ${parsed.maxTokens},
  tags: ${JSON.stringify(parsed.tags)},
};

export const RAW_SKILL_PROMPT = \`${content.replace(/`/g, '\\`')}\`;
`;
      default:
        return content;
    }
  }, [format, content, parsed]);

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(exportCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const extensions: Record<ExportFormat, string> = {
      skillmd: `${parsed.name}.skill.md`,
      mcp: `${parsed.name}.mcp.json`,
      openai: `${parsed.name}.tool.json`,
      python: `${parsed.name.replace(/-/g, '_')}_skill.py`,
      typescript: `${parsed.name.replace(/-/g, '_')}.skill.ts`,
    };
    const mimeTypes: Record<ExportFormat, string> = {
      skillmd: 'text/markdown',
      mcp: 'application/json',
      openai: 'application/json',
      python: 'text/x-python',
      typescript: 'text/typescript',
    };

    const blob = new Blob([exportCode], { type: mimeTypes[format] });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = extensions[format];
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
      <div className="bg-surface border border-line rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col font-sans max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-line bg-surface-2">
          <div className="flex items-center gap-2.5">
            <FileCodeIcon size={18} className="text-accent-bright" />
            <h2 className="text-sm font-bold text-ink">Export & Distribute Skill</h2>
            <span className="text-2xs font-mono px-2 py-0.5 rounded bg-accent/15 text-accent-bright font-semibold">
              {parsed.name}
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-surface-3 text-ink-muted hover:text-ink transition-colors cursor-pointer"
          >
            <XIcon size={16} />
          </button>
        </div>

        {/* Format Selector Pills */}
        <div className="px-6 py-3 border-b border-line bg-base flex flex-wrap items-center gap-2">
          <span className="text-xs text-ink-muted font-medium mr-1">Target Format:</span>
          {[
            { id: 'mcp', label: 'MCP Tool JSON' },
            { id: 'openai', label: 'OpenAI Schema' },
            { id: 'typescript', label: 'TypeScript (TS)' },
            { id: 'python', label: 'Python Wrapper' },
            { id: 'skillmd', label: 'Raw .skill.md' },
          ].map((item) => (
            <button
              key={item.id}
              onClick={() => setFormat(item.id as ExportFormat)}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-all cursor-pointer ${
                format === item.id
                  ? 'bg-accent text-white font-semibold shadow-sm'
                  : 'bg-surface-2 text-ink-muted hover:text-ink hover:bg-surface-3 border border-line'
              }`}
            >
              {item.label}
            </button>
          ))}
        </div>

        {/* Code Preview Box */}
        <div className="p-6 flex-1 overflow-hidden flex flex-col min-h-64">
          <div className="flex-1 rounded-xl bg-base border border-line p-4 font-mono text-xs text-ink overflow-auto select-text leading-relaxed">
            <pre className="whitespace-pre">{exportCode}</pre>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-line bg-surface-2">
          <div className="text-3xs text-ink-dim font-mono">
            {exportCode.split('\n').length} lines • {exportCode.length} characters
          </div>
          <div className="flex items-center gap-3">
            <button onClick={onClose} className="btn-outline text-xs py-1.5 px-4">
              Close
            </button>
            <button onClick={handleCopy} className="btn-outline text-xs py-1.5 px-4 flex items-center gap-1.5">
              {copied ? <CheckIcon size={13} className="text-ok" /> : <FileCodeIcon size={13} />}
              <span>{copied ? 'Copied!' : 'Copy Code'}</span>
            </button>
            <button onClick={handleDownload} className="btn-primary text-xs py-1.5 px-4 shadow-sm">
              Download File
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
